---
title: "ABC"
output: html_document
date: "2023-11-21"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("~/R/library.R")

```

```{r ABC RNA}
wdir="~/workspace/e.Blastocyst-K27ac/3.HiC/3.ABC-analysis"

paste0(wdir,"/merge.enhancer.tab") %>% read.tab(header=T)-> enhancer.tab


read.tab("~/workspace/e.Blastocyst-K27ac/5.RNA/1.Stringtie/all.samples.TPM.txt") -> tpm

merge(enhancer.tab,tpm) -> exp.enh

i="TE"
l=length(which(exp.enh[,i]==0))

exp.enh[order(exp.enh$ICM),c(i,paste0(i,"-control"),paste0(i,"-siP300"))][c(1:l,(dim(exp.enh)[1]-l+1):dim(exp.enh)[1]),] -> temp
temp[,i] = ifelse(temp[,i]==0,"None","EP") %>% factor
melt(temp,id.vars = i,variable.name = "condition",value.name = "TPM") -> temp
temp$log2TPM = log2(temp$TPM + 1)
colnames(temp)[1] = "flag"

ggplot(temp) + geom_boxplot(aes(x=flag,fill=condition,y=log2TPM),outlier.size = 0.5) +
    ggtitle(paste0(i)) +
    theme_bw() + theme(aspect.ratio = 2)
ggsave(paste0(wdir,"/exp.ep",i,".siP300.pdf"),width = 5,height = 7)


exp.enh[which(exp.enh$ICM==0&exp.enh$TE!=0),c("ICM-control","TE-control")] %>% cbind("TE.spe") %>% `colnames<-`(c("ICM","TE","flag")) -> temp

exp.enh[which(exp.enh$ICM!=0&exp.enh$TE==0),c("ICM-control","TE-control")] %>% cbind("ICM.spe") %>% `colnames<-`(c("ICM","TE","flag"))  %>% rbind(temp) -> temp

melt(temp,id.vars = "flag",variable.name = "sample",value.name = "TPM") -> temp
temp$log2TPM = log2(temp$TPM + 1)

ggplot(temp) + geom_boxplot(aes(x=flag,fill=sample,y=log2TPM),outlier.size = 0.5) +
    ggtitle("enhancer-promoter gene exp ") + xlab("has enhancer promoter") +
    theme_bw() + theme(aspect.ratio = 2)
ggsave(paste0(wdir,"/exp.ICM-TE.EPcompare.pdf"),width = 5,height = 7)
```

```{r distance}
read.tab("~/workspace/e.Blastocyst-K27ac/3.HiC/3.ABC-analysis/cat.EnhancerPredictions.txt",sep=",") -> cdata
cdata$distance = (cdata$TargetGeneTSS - (cdata$start+cdata$end)/2) %>% abs()

ggplot(cdata) +geom_density(aes(x=distance,color=CellType)) +
     scale_x_log10(labels = scales::label_number(suffix = "K", scale = 1e-3)) +annotation_logticks() +
    theme_bw() + theme(aspect.ratio = 3/4)

ggsave("~/workspace/e.Blastocyst-K27ac/3.HiC/3.ABC-analysis/ep.distance.pdf",width = 5,height = 4)

```

```{r cat.EnhancerPredictionsFull.txt}
wdir="~/workspace/e.Blastocyst-K27ac/3.HiC/3.ABC-analysis"
paste0(wdir,"/cat.EnhancerPredictionsFull.txt") %>% read.tab -> cdata

dcast(cdata[,c("TargetGene","CellType","ABC.Score")],TargetGene~CellType,value.var = "ABC.Score",fun.aggregate = sum) -> temp
temp[is.na(temp)] = 0

candidate.genes = c("Sox2","Tfap2c","Cdx2","Otx2","Pou5f1","Gata4","Gata3","Gata6","Klf3")
ggplot() + geom_point(aes(x=ICM,y=TE),temp,alpha=0.5,color="grey") +
    geom_point(aes(x=ICM,y=TE),temp[temp$TargetGene %in% candidate.genes,],color="red") +
    geom_text_repel(aes(x=ICM,y=TE,label=TargetGene),temp[temp$TargetGene %in% candidate.genes,],color="red") +
    xlab("Total ABC score in ICM") + ylab("Total ABC score in TE") +
    theme_pubr(border = T) + theme(aspect.ratio = 1)



data.table::dcast(setDT(cdata[,c("TargetGene","CellType","ABC.Score","TargetGeneExpression")]),TargetGene~CellType,value.var = c("ABC.Score","TargetGeneExpression"),fun.aggregate = list(sum,mean),fill=0) -> temp
rownames(temp) = temp$TargetGene
temp[,c(2,3,8,9)] %>% t %>% scale %>% t %>% data.frame()-> temp2
pheatmap(temp2,cluster_rows = T,cluster_cols = T,show_rownames = F,show_colnames = T,
         width = 2,height = 10,
         filename = paste0(wdir,"/pheatmap_ABCscore_exp.pdf"))

#distance
cdata[,c("CellType","distance")] -> temp
temp$distance %<>% add(10) %>% log10
ggplot(temp) + geom_density(aes(x=distance,color=CellType)) +
    annotation_logticks(sides = "b") + theme_bw() + theme(panel.grid = element_blank(),aspect.ratio = 3/4,text = element_text(family = "Arial",color="black"))
ggsave(paste0(wdir,"/density_distance.pdf"))


```

