---
title: "peak stat"
output: html_document
date: "2023-12-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("~/R/library.R")

sample=c("8cell","Morula","ICM","TE")
fills="pink"
```

```{r peaks length distribution}
wdir="~/workspace/e.Blastocyst-K27ac/4.callPeaks/2.MACS2-encode-K27ac-q5"
wdir="~/workspace/e.Blastocyst-K27ac/4.callPeaks/4.MACS2-narrow-q5/"
read.tab(cmd=paste0("cat ",wdir,"/*[laME]_K27ac_peaks.narrowPeak")) ->cdata
cdata$length = (cdata$V3-cdata$V2)
cdata$sample = str.split(cdata$V4,"_")[,1] %>% factor(levels=c("8cell","Morula","ICM","TE"))

ggplot(cdata) + geom_density(aes(x=length,color=sample)) +
    theme_pubr(border = T) + theme(aspect.ratio = 3/4) + scale_y_continuous(expand = c(0, 0)) +
    scale_x_log10(labels = scales::label_number(suffix = "K", scale = 1e-3),expand = c(0, 0),limits=c(100,80000)) +annotation_logticks(sides = "b")
ggsave(paste0(wdir,"/K27ac_peaks.length.pdf"),width=5,height = 4)


ggplot(cdata) + geom_boxplot(aes(x=sample,y=length,fill=sample),outlier.size = 0.2) +
    theme_pubr(border = T) + theme(aspect.ratio = 5/3) +
    scale_y_log10(labels = scales::label_number(suffix = "K", scale = 1e-3)) +annotation_logticks(sides = "l")
ggsave(paste0(wdir,"/K27ac_peaks.length.boxplot.pdf"),width=5,height = 4)



```

```{r peaks pie }
wdir="~/workspace/e.Blastocyst-K27ac/4.callPeaks/4.MACS2-narrow-q5"
paste0(wdir,"/K27ac.promoter.stat") %>% read.tab ->cdata
cdata$distal = cdata$total-cdata$promoter
cdata[,c(1,2,5)] %>% melt(.,id.vars = "stage",variable.name = "flag",value.name = "value") -> cdata2



# 绘制饼图
ggplot(cdata2, aes(x = "", y = value, fill = flag)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar("y", start = 0) +
  labs(title = "Pie K27ac peaks", fill = "Category") +
    facet_wrap(~stage,ncol=1, scales = "free") +
    #geom_text(stat = "identity", aes(label = scales::percent(..prop..)), position = position_stack(vjust = 0.5))
  theme_minimal() +theme(axis.text.x = element_blank()) +xlab("") +ylab("")

ggsave(paste0(wdir,"/K27ac.promoter.stat.pie.pdf"),width=4,height = 8)

#从morula继承到ICM、TE和both的比例
wdir="~/workspace/e.Blastocyst-K27ac/4.callPeaks/4.MACS2-narrow-q5/6.K27ac-ICM-TE"
paste0(wdir,"/retain.ratio.tab") %>% read.tab ->cdata
cdata$sample %<>% factor(levels = c("ICM-TE","ICM","TE"),labels = c("Both","ICM-specific","TE-specific"))
ggplot(cdata, aes(x = "", y = value, fill = flag)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar("y", start = 0) +
  labs(title = "K27ac peaks from morula", fill = "") +
    facet_wrap(~sample,ncol=1, scales = "free") +
   geom_text(stat = "identity", aes(label = scales::percent(ratio)), position = position_stack(vjust = 0.5),size=3)+
  theme_minimal() +theme(axis.text.x = element_blank()) +xlab("") +ylab("")

ggsave(paste0(wdir,"/retain.ratio.pie.pdf"),width=4,height = 8)

```

```{r peaks total length}
peaks.stat = "/home/qszhu/workspace/e.Blastocyst-K27ac/4.callPeaks/4.MACS2-narrow-q5/K27ac.peaks.stat"
peaks.stat %>% read.tab() ->cdata

cdata$hm %<>%  factor(levels = "K27ac")
cdata$stage %<>%factor(levels = c("8cell","Morula","ICM","TE"))
ggplot(cdata) +
    geom_bar(aes(x=stage,weight=ratio,fill=hm),position = position_dodge2(),
         width = 0.7,colour="black",linewidth=0.1) +
    xlab("")+
    scale_fill_manual(values="darkgreen")+
    scale_y_continuous(labels=scales::percent_format(),
                   #breaks = seq(0,0.08,0.02),expand = c(0,0),limits = c(0,0.08),
                   name = paste0("Percentage in genome")) +
    theme_zhu(axis.text.x = element_text(angle=45,hjust=1),
          aspect.ratio = 4/4)


ggsave(filename = paste0(peaks.stat,".pdf"),width = 7,height = 3.6)

ggplot(cdata) +
    geom_bar(aes(x=stage,weight=number,fill=hm),position = position_dodge2(),
         width = 0.7,colour="black",linewidth=0.1) +
    xlab("")+
    scale_fill_manual(values=fills)+
    scale_y_continuous(
                   name = paste0("peaks' number")) +
    facet_wrap(~hm,ncol = 3,scales = 'free') +
    theme_zhu(axis.text.x = element_text(angle=45,hjust=1,color = "black"),
          aspect.ratio = 4/4)
ggsave(paste0(peaks.stat,".number.pdf"),width = 7,height = 3.6)
ggplot(cdata) +
    geom_bar(aes(x=stage,weight=length,fill=hm),position = position_dodge2(),
         width = 0.7,colour="black",linewidth=0.1) +
    xlab("")+
    scale_fill_manual(values=fills)+
    scale_y_continuous(  name = paste0("average length")) +
    facet_wrap(~hm,ncol = 3,scales = 'free') +
    theme_zhu(axis.text.x = element_text(angle=45,hjust=1,color = "black"),
          aspect.ratio = 4/4)
ggsave(paste0(peaks.stat,".length.pdf"),width = 7,height = 3.6)
```


```{r peaks distance to boundary}
read.tab("~/workspace/e.Blastocyst-K27ac/3.HiC/8.IS/1.cat_boundary/K27ac.distance.tab") -> cdata

ggplot(cdata) +geom_density(aes(x=distance,color=peak)) +
    facet_wrap(~boundary,nrow=1) +
    xlim(10000,1000000) +
    scale_x_log10()


cdata$Dist = cut(cdata$distance, breaks = c(-2, 25000, 50000, 100000, 200000, 500000), labels = c("25k\n(boundary)", "50k", "100k", "200k", "500k"))

ggplot(cdata) +geom_bar(aes(x = Dist,fill=peak), stat = "count", position = "dodge2")+
    facet_wrap(~boundary,nrow=1,scales = "free") + theme_bw()

ggsave("~/workspace/e.Blastocyst-K27ac/3.HiC/8.IS/1.cat_boundary/K2ac.distance.bar.pdf",width = 7,height = 3.6)


library(dplyr)
read.tab("~/workspace/e.Blastocyst-K27ac/3.HiC/8.IS/1.cat_boundary/K27ac.distance.tab") -> cdata
cdata$Dist = cut(cdata$distance, breaks = c(-2,seq(25000,500000,25000)), labels = seq(25000,500000,25000))
cdata2 <- cdata %>% group_by(boundary, peak,Dist) %>% count()
total_counts <- cdata2 %>% group_by(boundary,peak) %>% summarise(total = sum(n))
cdata3 <- cdata2 %>% left_join(total_counts, by = c("boundary","peak")) %>% mutate(percentage = n / total)

ggplot(cdata3) +geom_bar(aes(x = Dist,fill=peak,y=percentage), position = "dodge2", stat = "identity")+
    facet_wrap(~boundary,nrow=1,scales = "free") + theme_bw() + theme(axis.text.x = element_text(angle=45,hjust=1),aspect.ratio = 1/1)

ggplot(cdata3) + geom_point(aes(x=Dist,y=percentage,color=peak)) +
    #geom_line(aes(x=Dist,y=percentage,color=peak,group=peak))+
    geom_smooth(aes(x=Dist,y=percentage,color=peak,group=peak)) +
    xlab("distance") +
    facet_wrap(~boundary,nrow=2) + theme_bw() + theme(aspect.ratio = 1/2, axis.text.x = element_text(angle=45,hjust=1))

ggsave("~/workspace/e.Blastocyst-K27ac/3.HiC/8.IS/1.cat_boundary/K27ac.distance.smooth.pdf",width = 7,height = 3.6)



#relative distance
wdir="~/workspace/e.Blastocyst-K27ac/3.HiC/8.IS/1.cat_boundary"
paste0(wdir,"/K27ac.reldist.tab") %>% read.tab() -> cdata

ggplot(cdata) + geom_point(aes(x=reldist,y=fraction,color=peak)) +
    #geom_line(aes(x=reldist,y=fraction,color=peak))+
    xlab("relative distance") +
    geom_smooth(aes(x=reldist,y=fraction,color=peak)) +
    facet_wrap(~boundary,nrow=2) + theme_bw() + theme(aspect.ratio = 1/2)
ggsave(paste0(wdir,"/K27ac.reldist.smooth.pdf"),width = 7,height = 3.6)
```

```{r peaks in promoter LTR}
wdir="~/workspace/e.Blastocyst-K27ac/4.callPeaks/4.MACS2-narrow-q5/6.K27ac-ICM-TE"
key="CGI"
df = paste0(wdir,"/",key,".ratio.tab") %>% read.tab()
df$ratio %<>% multiply_by(100)
df = df[!grepl("chr[XYM]",df$chr),]

temp = data.table(df)
temp = temp[,.(mean=mean(ratio),sem=sd(ratio)/sqrt(length(ratio))),by=.(flag)]
temp = data.frame(temp)


ggplot() +  geom_bar(data=temp,aes(x=flag,weight=mean),fill="skyblue",
                     position = position_dodge2(width = 0.5),width = 0.8) +
    geom_errorbar(data=temp,aes(x=flag, ymin=mean-sem, ymax=mean+sem),
                  width=0.4,alpha=1) +
    geom_jitter(data=df,aes(x=flag,y=ratio,fill=flag),
                position = position_jitterdodge(jitter.width = 0.4)) +
    ggsignif::geom_signif(aes(x=flag,y=ratio,fill=flag),df,
            comparisons = list(c("both","ICM"),c("both","TE")),y_position = c(6,7),test="t.test")+
    labs(x = "", y = "Percentage of peaks number") +
    ggtitle(paste0("Peaks in ",key)) +
    theme_bw() + theme(aspect.ratio = 2, axis.text.x = element_text(angle=45,hjust=1))

ggplot2::ggsave(paste0(wdir,"/",key,".ratio.pdf"),width = 5,height = 5,device = cairo_pdf)




```


